### ISSUE TITLE
Sometimes can't find sub templates

### ISSUE THREAD

**Issue by mrLSD** [kaj/ructe#10]
For some reason sub templates can't find.
For example I have templates:
```
templates/admin/pages/index.rs.html
templates/admin/pages/create.rs.html
```

compile ok.
Create new template:
```
templates/admin/pages/new.rs.html
@use admin::handlers::HeaderData;
@(h: &HeaderData)
```

and in code invoke it:
`render(res, |o| templates::admin::pages::new(o, &header))`

and I have got error:

```
   Compiling nickel-cms v0.3.0 (file:///home/evgeny/rs/nickel-cms)
error[E0425]: unresolved name `templates::admin::pages::new`
  --> src/admin/handlers/pages.rs:38:21
   |
38 |     render(res, |o| templates::admin::pages::new(o, &header))
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unresolved name

error: aborting due to previous error

```

but, if at existed template I include:
`@:new(h)` and compile it - it compile ok. Then remove it. Compile project again - Template founded.
It's really offensive bug.

**Comment by kaj** [comment]
Ah, yes.  I've seen it to, and it is annoying.  I think it can be solved just by adding a `cargo:rerun-if-changed` output for `indir` itself in `compile_static_files`, but I'm not sure how cargo will handle a directory there, so we will have to experiment.

Can you try that out and maybe submit a PR?  Otherwise, I'll try it when I can find some time.

**Comment by mrLSD** [comment]
I'll try.
