### ISSUE TITLE
Static files can't work with module

### ISSUE THREAD

**Issue by samlink** [kaj/ructe#135]
html:
@use super::statics::general_js;
...
<script type="module" src="/static/@general_js.name"></script>

general.js like this :
import {notifier} from '/assets/js/parts/notifier.mjs';
import {alert_confirm} from "/assets/js/parts/alert.mjs";

let theme_name = "blue";
let class_theme = document.querySelector('body').className;
let theme_name = class_theme.split('.')[0];
...

App can be compiled successfully, but when i run it in brower, it show error:
Loading module from (url) was blocked because of a disallowed MIME type (“”)'

I can't solve it. I‘ll appreciate your help very much.

**Comment by kaj** [comment]
... or, possibly, none of the mime, warp, or tide features of ructe is enabled in your project?  If so, try adding `features = ["mime03"]` to the ructe dependency in your `Cargo.toml`.

**Comment by samlink** [comment]
Thank you for your reply. I'll say it simply:
in my general.js, there is only one sentence：
    console.log('dd'); 

when i use <script type="module"..>, i ran into this error. when i don't use "module" type, all is ok.

**Comment by samlink** [comment]
i use actix-wb.

**Comment by kaj** [comment]
Without any `import` statements in your `general.js`?  Strange.

If I add this line to the head, as line 12 in `examples/actix/templates/page.rs.html`:

```
    <script type="module" src="/static/@foo_js.name"></script>
```

... and writes a single line `console.log("hello");` as `examples/actix/statics/foo.js`, it seems to work fine?

Therefore I assumed the problem was with the `imports`, as ructe don´t rewrite the js file in any way, so it can't fix any path names for further imports.

**Comment by samlink** [comment]
Yes, there was something wrong with import path. Thank you very much for your help.
