### ISSUE TITLE
Not informative error messages

### ISSUE THREAD

**Issue by mrLSD** [kaj/ructe#8]
Error message completely not informative.

Template:
```
@use admin::handlers::main::HeaderData;
@(h: &HeaderData)
@if h.is_active("main") == true { active }
```

Error message:
```
   Compiling nickel-cms v0.3.0 (file:///home/evgeny/rs/nickel-cms)
warning: Template parse error in "/home/evgeny/rs/nickel-cms/templates/admin/layout/sidebar.rs.html": End of file
error[E0432]: unresolved import `templates::admin::layout::sidebar`
 --> /home/evgeny/rs/nickel-cms/target/debug/build/nickel-cms-ce85cbf7f3e4b8e4/out/templates/admin/layout/template_header.rs:4:5
  |
4 | use templates::admin::layout::sidebar;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `sidebar` in `templates::admin::layout`

error: aborting due to previous error

error: Could not compile `nickel-cms`
```

or like that:
```
warning: Failed to parse template "/home/evgeny/rs/nickel-cms/templates/admin/helpers/active.rs.html": Size(114) needed
```

It's impossible debugging with these messages.
I suggest strongly improve error reporting messages.

**Comment by kaj** [comment]
Agreed.  The first one would be easy enough to fix by failing the build job when there is an error in compiling a template.  That would mean only seeing errors like the second kind, and never attempt to actually compile the rust code that uses the templates when template compilation fails.

To improve the second kind require learning to provide specific parser error messages from the [nom](https://crates.io/crates/nom) parser generator.  I'm not even sure how good support nom has for that yet, but I will look into it.

**Comment by kaj** [comment]
I've been experimenting some more with this (without committing any code).  It seems to be possible to get rather good error information from nom, but the parser has to be partially reconstructed; I have typically created largish sub-parsers (e.g. one parser for a complete `@for item in items { something }` and one for `@if condition { something }` and joined them with `alt!`.  This won't work since the generated parser will ignore errors in all but the last branch.  It can be fixed by using the `switch!` macro rather than `alt!`.  But I still have problem with looping constructs, which will just assume the loop ended on any error, rather than reporting the actual error.

I have not given up, but this may take some time.

**Comment by kaj** [comment]
I think this is done for now (although not released yet).
